apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rollouts-demo-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Rollout"
    name:       "rollouts-demo"
  updatePolicy:
    updateMode: "Auto"
