apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo-promote
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: nginx:1.20.0 # 1.19.0 -> 1.20.0
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 75
        - pause: {}
        - setWeight: 100
